config/routes.rb
Tyler::Application.routes.draw do
  root to: 'sessions#new'

  resource :session, controller: 'sessions', only: [:new, :create, :destroy]
  match '/sign_in', controller: 'sessions', action: 'new', as: 'sign_in'
  match '/sign_out', controller: 'sessions', action: 'destroy', as: 'sign_out'

  resources :users, only: [:show]

  resources :registrations, only: [:new, :create]
  match '/sign_up', controller: 'registrations', action: 'new', as: 'sign_up'

  match '/validate', controller: 'tokens', action: 'validate', as: 'validate'

  namespace :api do
    resources :authorizations
  end

end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base
  before_create :generate_key

  private

  def generate_key
    self.key = SecureRandom.urlsafe_base64(64)
  end
end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  belongs_to :created_by_api_key, :class_name => "ApiKey"
  has_one :registration
  has_one :user, :through => :registration

  validates_presence_of :code
  validates_uniqueness_of :code

  store :properties
end

app/models/consumer.rb
class Consumer < ActiveRecord::Base
end

app/models/registration.rb
class Registration < ActiveRecord::Base
  store :properties
  belongs_to :authorization
  belongs_to :user
  accepts_nested_attributes_for :user

  validate :check_properties, :on => :create

  def user
    super || build_user
  end

  def properties
    existing = super

    APP_CONFIG["registration_properties"].each do |property|
      existing[property] ||= ""
    end

    existing
  end

  private

  def check_properties
    # Lookup configured registration properties
    registration_properties = APP_CONFIG["registration_properties"]

    # Find the associated Authorization
    self.authorization = Authorization.find_by_code(code)

    # If an Authorization was found ensure that each registration property matches and record
    # whether or not it has been used by another user
    if authorization
      authorization_used = authorization.user.present?
      registration_valid = registration_properties.all? do |property|
        properties[property] == authorization.properties[property]
      end
    else
      registration_valid = false
    end

    # If the Authorization is unused and the registration properties match the authorization properties then
    # procceed without validation eror.
    if !registration_valid || authorization_used
      errors.add(:registration, "information is not valid or is associated with an existing user")
    end
  end
end

app/models/token.rb
class Token < ActiveRecord::Base
  belongs_to :user
  belongs_to :consumer

  before_create :generate_token

  def ensure_current!
    if updated_at < 5.minutes.ago
      generate_token
      save!
    end
  end

  def expired?
    updated_at < 5.minutes.ago
  end

  private

  def generate_token
    self.token = SecureRandom.urlsafe_base64
  end
end

app/models/user.rb
require 'ostruct'

class User < ActiveRecord::Base
  include Clearance::User
end

app/controllers/api/authorizations_controller.rb
class Api::AuthorizationsController < ApplicationController
  respond_to :json
  skip_before_filter :verify_authenticity_token

  def create
    api_key = ApiKey.find_by_key(params[:key])
    if api_key
      authorization = Authorization.create!(params_for_authorization.merge('created_by_api_key_id' => api_key.id))
      render :json => authorization.to_json
    else
      render :json => nil, :status => :not_found
    end
  end

  private

  def params_for_authorization
    other_properties = params[:authorization].reject { |k,v| k == 'code' }
    {
      'code' => params[:authorization][:code],
      'properties' => other_properties
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Authentication
  protect_from_forgery
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @registration = Registration.new
  end

  def create
    @registration = Registration.new(params[:registration])
    if @registration.save
      sign_in @registration.user
      redirect_to @registration.user
    else
      render "new"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController
  def new
    consumer = fetch_consumer(params[:consumer])
    if current_user
      redirect_after_sign_in(current_user, consumer)
    else
      render 'new'
    end
  end

  def create
    consumer = fetch_consumer(params[:session][:consumer])
    user = authenticate(params)
    if user.nil?
      flash_failure_after_create
      render 'new', :status => :unauthorized
    else
      sign_in(user)
      redirect_after_sign_in(user, consumer)
    end
  end

  private

  def redirect_after_sign_in(user, consumer)
    if consumer
      redirect_to_consumer(consumer, user)
    else
      redirect_to(user)
    end
  end

  def fetch_consumer(name)
    if name.nil? || name.empty?
      nil
    else
      consumer = Consumer.find_by_name(name)
      raise "Invalid consumer #{name} was provided." if consumer.nil?
      consumer
    end
  end

  def fetch_token(consumer, user)
    Token.find_or_create_by_consumer_id_and_user_id(consumer.id, user.id)
  end

  def redirect_to_consumer(consumer, user)
    token = fetch_token(consumer, user)
    token.ensure_current!
    redirect_to "#{consumer.return_url}?token=#{token.token}"
  end
end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  def validate
    @token = Token.find_by_token(params[:token])
    if @token.nil? || @token.expired?
      render :json => nil, :status => :not_found
    else
      render :json => TokenSerializer.new(@token).to_json
    end
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  def show
    #TODO: Ensure that only the logged-in user can see their own user page
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tyler</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <span class="brand">
            <%= APP_CONFIG['system_name'] %>
          </span>
          <ul class="nav pull-right">
            <li class="divider-vertical"></li>
            <li class="dropdown">
              <% if signed_in? %>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="icon-user icon-white"></i>
                  <%= current_user.email %>
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to "Sign out", sign_out_path %>
                  </li>
                </ul>
              <% else %>
                <%= link_to "Sign in", sign_in_path %>
              <% end %>
            </li>
          </div>
        </div>
      </div>
    </div>
    <div class="container page">
      <% flash.each do |key, value| -%>
        <div class="alert <%= key %>"><%= value %></div>
      <% end -%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form.section "Registration Information" do %>
  <%= form.fields_for :registration do |registration_form| %>
    <% @registration_properties.each do |registration_property| %>
      <%= registration_form.text_field registration_property %>
    <% end %>
  <% end %>
<% end %>
<%= form.section "Your New Account" do %>
  <%= form.text_field :email, :type => "email" %>
  <%= form.password_field :password %>
<% end %>

app/views/users/new.html.erb
<div class="row">
  <div class="span1">&nbsp;</div>
  <div class="span8">
    <%= form_for @user, :builder => BootstrapFormBuilder do |form| %>
      <%= render :partial => '/users/form', :object => form %>
      <%= form.submit 'Sign up' %>
    <% end %>
  </div>
  <div class="span4">
    <h3>Help</h3>
    <p>
      Helpful information about registering for an account goes here. Talk about competing the required registration information, entering a valid e-mail address, selecting a new password, etc.
    </p>
  </div>
  <div class="span3">&nbsp;</div>
</div>